# Generated by Django 4.2.2 on 2023-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='doctors',
            field=models.ManyToManyField(related_name='exercise', to='exercises.doctor', verbose_name='Список докторов'),
        ),
    ]
