# Generated by Django 4.2.2 on 2023-08-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_list', to='exercises.doctor', verbose_name='Доктор')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Упражнение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Назначенное упражнение',
                'verbose_name_plural': 'Назначенные упражнения',
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='exercisepatient',
            constraint=models.UniqueConstraint(fields=('patient', 'exercise'), name='unique_patient'),
        ),
    ]
